const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8'),source=html.split('// ── BILLIARDS ENGINE v310 ──')[1].split('// ── END BILLIARDS ENGINE ──')[0],ctx={Math,performance};vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function calcPts(cards){'),html.indexOf('// v286: normal battles'))+source+';this.api={BB_CFG,bbRole,bbBody,bbPoints,bbCreate,bbStart,bbShoot,bbPhysics,bbStep,bbJoin,bbBreak,bbOutcome,bbFollowingPlayer,bbPlace,bbValidPlacement,bbPlacementOptions,bbChoosePlacement,bbCandidates,bbEvaluate,bbRay};',ctx);
const {BB_CFG,bbRole,bbBody,bbPoints,bbCreate,bbStart,bbShoot,bbPhysics,bbStep,bbJoin,bbBreak,bbOutcome,bbFollowingPlayer,bbPlace,bbValidPlacement,bbPlacementOptions,bbChoosePlacement,bbCandidates,bbEvaluate,bbRay}=ctx.api;
function game(parts){const s=bbCreate('normal',()=>.5);s.bodies=parts.map((b,i)=>bbBody(i+1,b[0],b[1],b[2].map((n,j)=>({x:j*40,y:0,n}))));s.nextId=100;bbStart(s);return s;}
function settle(s){for(let i=0;i<1300&&s.moving;i++)bbStep(s);assert.equal(s.moving,false);}
function placeAll(s){let count=0;while(s.placing){assert(++count<=12);const p=bbChoosePlacement(s,()=>.5);assert(p);assert(bbPlace(s,s.placer,p.x,p.y));}}
function numbers(s){return [...s.bodies.flatMap(b=>b.parts.filter(p=>p.n).map(p=>p.n)),...s.returnBalls].sort((a,b)=>a-b);}
const inventory=[1,1,2,2,2,3,3,3,4,4,5,5];
for(let seed=1;seed<=20;seed++){let x=seed;const rng=()=>((x=(x*1664525+1013904223)>>>0)/4294967296),s=bbCreate('normal',rng);assert.equal(s.bodies.length,13);assert(s.bodies.every(b=>b.parts.length===1));assert.equal(s.bodies.filter(b=>b.sum===0).length,1);assert.deepEqual(numbers(s),inventory);for(let i=0;i<13;i++)for(let j=i+1;j<13;j++)assert(Math.hypot(s.bodies[i].x-s.bodies[j].x,s.bodies[i].y-s.bodies[j].y)>46);}
// First real cue impact weakens but preserves the cluster; a separate second shot splits it.
let s=game([[220,530,[0]],[180,380,[3,2,4]]]);const original=numbers(s);assert(bbShoot(s,-Math.PI/2,.55));settle(s);assert.equal(s.bodies.length,2);assert.equal(s.bodies[1].cueHits,1);assert.equal(s.events.filter(e=>e.kind==='weaken').length,1);assert(!s.events.some(e=>e.kind==='break'));assert.deepEqual(numbers(s),original);
Object.assign(s.bodies[0],{x:220,y:530,vx:0,vy:0});Object.assign(s.bodies[1],{x:180,y:380,a:0,vx:0,vy:0,w:0});bbPhysics(s,0);assert(bbShoot(s,-Math.PI/2,.55));for(let i=0;i<500&&!s.events.some(e=>e.kind==='break');i++)bbStep(s);assert(s.events.some(e=>e.kind==='break'));assert.equal(s.bodies.length,4);assert(s.bodies.every(b=>b.parts.length===1&&b.cueHits===0));assert.deepEqual(numbers(s),original);for(let i=0;i<35;i++)bbStep(s);assert(s.bodies.every(b=>b.parts.length===1),'immediate rejoin after breaking');settle(s);assert.deepEqual(numbers(s),original);
// Resting/jittering contact across two components is ONE touch, even over many physics frames.
s=game([[120,134,[0]],[100,100,[3,2]]]);for(let i=0;i<60;i++){Object.assign(s.bodies[0],{x:120,y:134,vx:0,vy:0});Object.assign(s.bodies[1],{x:100,y:100,a:0,vx:0,vy:0,w:0});bbPhysics(s,BB_CFG.step);}assert.equal(s.bodies.length,2);assert.equal(s.bodies[1].cueHits,1);assert.equal(s.events.filter(e=>e.kind==='weaken').length,1);assert(!s.events.some(e=>e.kind==='break'));
// Genuine separation rearms that same cluster; touching a different component still splits all of it.
Object.assign(s.bodies[0],{x:400,y:650});bbPhysics(s,0);assert.equal(s.bodies[1].cueTouching,false);const target=bbPoints(s.bodies[1])[1];Object.assign(s.bodies[0],{x:target.x,y:target.y+39});bbPhysics(s,0);assert(s.events.some(e=>e.kind==='break'));assert.equal(s.bodies.length,3);
// Turn changes and further valid numeric joins preserve the weakened state, rather than repairing it.
s=game([[400,650,[0]],[100,100,[1,2]],[220,100,[3]]]);s.bodies[1].cueHits=1;const joined=bbJoin(s,s.bodies[1],s.bodies[2]);assert.equal(joined.cueHits,1);bbShoot(s,Math.PI/2,.08);settle(s);assert.equal(joined.cueHits,1);assert.equal(s.turn,1);const touch=bbPoints(joined)[0];Object.assign(s.bodies[0],{x:touch.x,y:touch.y+39});bbPhysics(s,0);assert(s.events.some(e=>e.kind==='break'));
s=game([[50,600,[0]],[180,260,[1,2,3]]]);s.bodies[1].a=.7;const before=bbPoints(s.bodies[1]);const pieces=bbBreak(s,s.bodies[1]);for(let i=0;i<3;i++){assert.equal(pieces[i].x,before[i].x);assert.equal(pieces[i].y,before[i].y);assert.equal(pieces[i].parts[0].n,before[i].n);}
// Real physics completes an intact 3-ball cluster with one numbered ball.
s=game([[220,530,[0]],[220,390,[1]],[180,260,[3,2,4]]]);s.turn=1;assert(bbShoot(s,-Math.PI/2,.8));settle(s);assert.deepEqual(Array.from(s.scores),[0,5]);assert(s.placing);assert.equal(s.placer,0);assert.deepEqual(Array.from(s.returnBalls).sort(),[1,2,3,4]);assert(!bbShoot(s,0,1));
// Placement guards and pause retain inventory and turn.
let p=bbPlacementOptions(s)[0],snapshot=JSON.stringify(s);assert(!bbPlace(s,1,p.x,p.y));assert(!bbPlace(s,0,-2,p.y));assert(!bbPlace(s,0,NaN,p.y));assert(!bbPlace(s,0,s.bodies[0].x,s.bodies[0].y));assert.equal(JSON.stringify(s),snapshot);s.paused=true;assert(!bbPlace(s,0,p.x,p.y));const frozen=JSON.stringify(s);for(let i=0;i<100;i++)bbStep(s);assert.equal(JSON.stringify(s),frozen);s.paused=false;
const retained=numbers(s);assert(bbPlace(s,0,p.x,p.y));assert(!bbPlace(s,0,p.x,p.y));assert.equal(s.returnBalls.length,3);placeAll(s);assert.deepEqual(numbers(s),retained);assert.equal(s.turn,1);assert.equal(s.shots,1);
// Two-, three-, and four-ball tens score correctly, including both reported regressions.
for(const [values,points,label]of [[[5,5],1,'役なし'],[[5,4,1],1,'役なし'],[[5,3,2],1,'役なし'],[[4,4,2],2,'ワンペア'],[[1,1,3,5],2,'ワンペア'],[[1,2,2,5],2,'ワンペア'],[[1,1,4,4],3,'ツーペア'],[[2,2,3,3],3,'ツーペア'],[[2,2,2,4],4,'スリーカード'],[[1,3,3,3],4,'スリーカード'],[[1,2,3,4],5,'ストレート']]){assert.equal(bbRole(values).points,points);assert.equal(bbRole(values).label,label);for(const who of [0,1]){
 s=game([[220,600,[0]],[80,100,[values[0]]],[180,100,values.slice(1)]]);s.turn=who;const all=numbers(s);assert(bbShoot(s,Math.PI/2,.08));bbJoin(s,s.bodies[1],s.bodies[2]);settle(s);assert.equal(s.placer,1-who);assert.equal(s.nextShooter,who);assert.equal(s.returnBalls.length,values.length);assert.equal(s.scores[who],points);placeAll(s);assert.equal(s.turn,who);assert.equal(s.shots,1);assert.deepEqual(numbers(s),all);
}}
// Seven consecutive pair finishes (14 points) have no turn cap; a miss hands over.
for(const who of [0,1]){s=game([[220,600,[0]]]);s.turn=who;for(let shot=1;shot<=7;shot++){s.bodies=[bbBody(1,220,600,[{x:0,y:0,n:0}]),bbBody(2,80,100,[{x:0,y:0,n:1}]),bbBody(3,180,100,[{x:0,y:0,n:1},{x:40,y:0,n:3},{x:80,y:0,n:5}])];assert(bbShoot(s,Math.PI/2,.08));bbJoin(s,s.bodies[1],s.bodies[2]);settle(s);assert.equal(s.nextShooter,who);assert.equal(s.placer,1-who);p=bbPlacementOptions(s)[0];assert(!bbPlace(s,who,p.x,p.y));placeAll(s);assert.equal(s.turn,who);assert.equal(s.shots,shot);assert.equal(s.scores[who],shot*2);}s.bodies=[bbBody(1,220,600,[{x:0,y:0,n:0}])];bbShoot(s,Math.PI/2,.08);settle(s);assert.equal(s.turn,1-who);assert.equal(s.shots,0);}
// Invalid joins have zero side effects; over-ten, fifth-ball and incomplete fourth-ball contacts bounce.
for(const [left,right]of [[[5,2],[4]],[[4,3],[5]],[[1,1],[2,2]],[[1,1,2],[2,4]],[[1,1,2],[2,3]]])for(const who of [0,1]){
 s=game([[400,650,[0]],[100,100,left],[100,139,right]]);s.turn=who;const all=numbers(s),before=JSON.stringify(s);assert.equal(bbJoin(s,s.bodies[1],s.bodies[2]),null);assert.equal(JSON.stringify(s),before);
 s.bodies[2].vy=-100;s.moving=true;settle(s);assert.equal(s.scores[who],0);assert.equal(s.returnBalls.length,0);assert(!s.placing);assert.equal(s.bodies.length,3);assert.equal(s.merged,0);assert(s.events.some(e=>e.kind==='hit'));assert(!s.events.some(e=>e.kind==='burst'));assert.equal(s.turn,1-who);assert.deepEqual(numbers(s),all);
}
// Real moving collisions complete 5-4-1, 5-3-2 and 5-5, not just direct join calls.
for(const [single,cluster]of [[1,[5,4]],[2,[5,3]],[5,[5]]])for(const who of [0,1]){
 s=game([[220,530,[0]],[220,390,[single]],[cluster.length===1?220:180,260,cluster]]);s.turn=who;const all=numbers(s);assert(bbShoot(s,-Math.PI/2,.8));settle(s);assert.equal(s.scores[who],1);assert(s.shotTen);assert(s.placing);assert.equal(s.returnBalls.length,cluster.length+1);assert.equal(s.placer,1-who);placeAll(s);assert.equal(s.turn,who);assert.deepEqual(numbers(s),all);assert(bbShoot(s,Math.PI/2,.08));
}
// An over-ten bounce in the same shot never cancels a valid finish or creates another placement.
for(const who of [0,1]){
 s=game([[220,600,[0]],[80,100,[1]],[180,100,[5,4]],[80,300,[5,2]],[250,300,[4]]]);s.turn=who;const all=numbers(s),a=s.bodies.slice(1,3),b=s.bodies.slice(3,5);bbShoot(s,Math.PI/2,.08);bbJoin(s,...a);assert.equal(bbJoin(s,...b),null);settle(s);assert.equal(s.scores[who],1);assert.equal(s.nextShooter,who);assert.equal(s.placer,1-who);assert.equal(s.returnBalls.length,3);placeAll(s);assert.equal(s.turn,who);assert.equal(s.shots,1);assert.deepEqual(numbers(s),all);
}
// Several valid finishes return all original numbers to the same opposing placer.
s=game([[220,600,[0]],[80,100,[1]],[180,100,[5,4]],[80,300,[2]],[180,300,[5,3]]]);const multi=numbers(s),pairs=[s.bodies.slice(1,3),s.bodies.slice(3,5)];bbShoot(s,Math.PI/2,.08);for(const pair of pairs)bbJoin(s,...pair);settle(s);assert.equal(s.scores[0],2);assert.equal(s.returnBalls.length,6);assert.equal(s.placer,1);placeAll(s);assert.equal(s.turn,0);assert.deepEqual(numbers(s),multi);
// A winning exact-four finish ends after motion, with no placement or subsequent input.
s=game([[220,600,[0]],[80,100,[1]],[180,100,[2,3,4]]]);s.scores[0]=10;bbShoot(s,Math.PI/2,.08);bbJoin(s,s.bodies[1],s.bodies[2]);settle(s);assert.equal(s.phase,'ended');assert.equal(s.scores[0],15);assert(!s.placing);assert(!bbShoot(s,0,1));assert(!bbPlace(s,1,100,300));
// AI evaluates the same completion/bounce physics without changing live state.
s=game([[220,530,[0]],[220,390,[1]],[180,260,[3,2,4]]]);s.turn=1;snapshot=JSON.stringify(s);let best=-Infinity;for(const c of bbCandidates(s).slice(0,60))best=Math.max(best,bbEvaluate(s,c));assert(best>=1000);assert.equal(JSON.stringify(s),snapshot);assert(bbRay(s,-Math.PI/2)<140);
s=game([[220,530,[0]],[220,390,[5]],[220,260,[5]]]);assert(bbEvaluate(s,{angle:-Math.PI/2,power:.8})>=200);
// Full games retain precisely the same twelve digits through bounces, placements and joins.
for(const level of ['easy','normal','hard']){s=bbCreate(level,()=>.5);bbStart(s);for(let shot=0;shot<35;shot++){assert(bbShoot(s,shot*2.399,.6+(shot%3)*.2));settle(s);assert.deepEqual(numbers(s),inventory);assert(!s.events.some(e=>e.kind==='burst')); if(s.phase==='ended')break;placeAll(s);for(const b of s.bodies){assert(b.parts.length<=3);for(const p of bbPoints(b)){assert(Number.isFinite(p.x)&&Number.isFinite(p.y));assert(p.x>=19&&p.x<=421,JSON.stringify(p));assert(p.y>=19&&p.y<=s.h-19,JSON.stringify(p));}}assert.deepEqual(numbers(s),inventory);}}
console.log('PASS: exactly twelve digits, two-to-four-ball tens including 5-4-1 and 5-3-2, all ranks, unlimited successful turns, invalid joins bounce without loss or placement, opposing placer, pause/invalid input, two-contact cue breakup, sustained-contact debounce, persistent weakened state, win, AI, 105-shot inventory and stability.');
